import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import NavBar from '../components/nav-bar'
import NavDropdown from '../components/nav-dropdown'
import localFont from 'next/font/local'
import Footer from '@/components/footer'
import NavDropdownProviderWrapper from '@/wrapper/nav-wrapper'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const satoshi = localFont({
  src: [
    {
      path: '../../public/Fonts/Satoshi-Light.otf',
      weight: '300',
      style: 'normal'
    },
    {
      path: '../../public/Fonts/Satoshi-Regular.otf',
      weight: '400',
      style: 'normal'
    },
    {
      path: '../../public/Fonts/Satoshi-Bold.otf',
      weight: '700',
      style: 'normal'
    },
    {
      path: '../../public/Fonts/Satoshi-Black.otf',
      weight: '800',
      style: 'normal'
    }
  ],
  variable: '--nexa-font'
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${satoshi.variable}  antialiased`}>
        <NavDropdownProviderWrapper>
          <NavBar />
          {children}
          <Footer />
        </NavDropdownProviderWrapper>
      </body>
    </html>
  )
}
